cat:
	cat Makefile


mel:
	python3  try_melissa_one.py --addressline1 '4416 ash grove, sioux falls, sd' --postalcode 57103


# https://lookups.melissa.com/home/addresscheck/address/?address=4416+S+Ash+Grove+Ave%2C+Sioux+Falls%2C+SD%2C+57103-4914&suites=&freeForm=4416+S+Ash+Grove+Ave%2C+Sioux+Falls%2C+SD%2C+57103-4914&mak=3056348535&checkOption=append
